### ISSUE TITLE
Missing SoftPWM.h

### ISSUE THREAD

**Issue by VNuhaan** [YourproductSmarter/KISSLoRa-demo#9]
I tried to compile the KISSLoRa-demo_app, but I miss SoftPWM.h.

Where can I find the SoftPWM.h?

**Comment by jpmeijers** [comment]
Please follow the steps laid out in the main Readme of this repository. Everything you need, including how to install SoftPWM is documented there.

**Comment by VNuhaan** [comment]
My mistake, RTEFM! 

(Read The Entire Friendly Manual)
